.Dd $Mdocdate: May 13 2025 $
.Dt MUI 3
.Os
.Sh NAME
.Nm mui
.Nd minimalist UI
.Sh DESCRIPTION
.Sy mui 
is a minimalist UI library for X11 that utilizes xcb.
.sp
.Sh BASICS
Before doing anything the library must first be included then a window
can be created.
.Sh AUTHORS
Onana Onana Xavier Manuel 
.Em onanaxm@outlook.com
